def fetch_model_catalog() -> str: ...
def call_decoder(model_id: str, system_prompt: str, user_prompt: str, max_tokens: int) -> str: ...
def call_gliner(model_id: str, text: str) -> str: ...
def append_evidence_json(run_json: str) -> None: ...
def read_recent_evidence_json(limit: int) -> str: ...
